services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    container_name: api-store
    ports:
      - '5432:5432'
    # command:
    #   sh -c 'npm run start:dev'
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: $DB_NAME
    command: -p $DB_PORT
    logging:
      driver: none
